[package]
name = "parkour"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.12.1"
bevy_rapier3d = "0.23.0"
bevy_wasm_window_resize = "0.2.1"
rand = "0.8.5"

[features]
dev = [
  "bevy/dynamic_linking",
  "bevy/file_watcher",
  "bevy_rapier3d/debug-render-3d",
]
