[package]
name = "parkour"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.12.0", features = ["file_watcher"] }
bevy_rapier3d = { version = "0.23.0", features = ["debug-render-3d"] }
rand = "0.8.5"
